""" ht_libs constants. """


from os import environ

OAUTH_KEY = environ["HATTRICK_OAUTH_CONSUMER_KEY"]
OAUTH_SECRET = environ["HATTRICK_OAUTH_CONSUMER_SECRET"]


REQUEST_TOKEN_URL = "https://chpp.hattrick.org/oauth/request_token.ashx"
ACCESS_TOKEN_URL = "https://chpp.hattrick.org/oauth/access_token.ashx"
AUTHORIZE_URL = "https://chpp.hattrick.org/oauth/authorize.aspx"
BASE_URL = "https://chpp.hattrick.org/chppxml.ashx"
TOKEN_STATUS_URL = "https://chpp.hattrick.org/oauth/check_token.ashx"


ALL_FLAGS = [
    ["128", "Iraq", "IQ", "AS"],
    ["127", "Kuwait", "KW", "AS"],
    ["77", "Morocco", "MA", "AF"],
    ["106", "Jordan", "JO", "AS"],
    ["133", "Yemen", "YE", "AS"],
    ["118", "Algeria", "DZ", "AF"],
    ["105", "Andorra", "AD", "EU"],
    ["130", "Angola", "AO", "AF"],
    ["7", "Argentina", "AR", "SA"],
    ["129", "Azerbaijan", "AZ", "AS"],
    ["123", "Bahrain", "BH", "AS"],
    ["132", "Bangladesh", "BD", "AS"],
    ["124", "Barbados", "BB", "NA"],
    ["91", "Belarus", "BY", "EU"],
    ["44", "Belgium", "BE", "EU"],
    ["158", "Belize", "BZ", "NA"],
    ["139", "Benin", "BJ", "AF"],
    ["74", "Bolivia", "BO", "SA"],
    ["69", "Bosnia and Herzegovina", "BA", "EU"],
    ["160", "Botswana", "BW", "AF"],
    ["16", "Brazil", "BR", "SA"],
    ["136", "Brunei", "BN", "AS"],
    ["62", "Bulgaria", "BG", "EU"],
    ["167", "Burkina Faso", "BF", "AF"],
    ["125", "Cape Verde", "CV", "AF"],
    ["146", "Cameroon", "CM", "AF"],
    ["17", "Canada", "CA", "NA"],
    ["52", "Czech Republic", "CZ", "EU"],
    ["18", "Chile", "CL", "SA"],
    ["34", "People's Republic of China", "CN", "AS"],
    ["60", "Chinese Taipei", "TW", "AS"],
    ["19", "Colombia", "CO", "SA"],
    ["151", "Comoros", "KM", "AF"],
    ["81", "Costa Rica", "CR", "NA"],
    ["126", "Côte d’Ivoire", "CI", "AF"],
    ["131", "Montenegro", "ME", "EU"],
    ["147", "Cuba", "CU", "NA"],
    ["153", "Curaçao", "CW", "NA"],
    ["61", "Wales", "GB", "EU"],
    ["89", "Cyprus", "CY", "EU"],
    ["11", "Denmark", "DK", "EU"],
    ["141", "Qatar", "QA", "AS"],
    ["3", "Germany", "DE", "EU"],
    ["144", "Maldives", "MV", "AS"],
    ["73", "Ecuador", "EC", "SA"],
    ["56", "Estonia", "EE", "EU"],
    ["100", "El Salvador", "SV", "NA"],
    ["2", "England", "GB", "EU"],
    ["36", "Spain", "ES", "EU"],
    ["76", "Faroe Islands", "FO", "EU"],
    ["5", "France", "FR", "EU"],
    ["137", "Ghana", "GH", "AF"],
    ["166", "Grenada", "GD", "NA"],
    ["154", "Guam", "GU", "OC"],
    ["107", "Guatemala", "GT", "NA"],
    ["164", "Haiti", "HT", "NA"],
    ["30", "South Korea", "KR", "AS"],
    ["122", "Armenia", "AM", "AS"],
    ["50", "Greece", "GR", "EU"],
    ["99", "Honduras", "HN", "NA"],
    ["59", "Hong Kong", "HK", "AS"],
    ["58", "Croatia", "HR", "EU"],
    ["20", "India", "IN", "AS"],
    ["54", "Indonesia", "ID", "AS"],
    ["85", "Iran", "IR", "AS"],
    ["21", "Ireland", "IE", "EU"],
    ["38", "Iceland", "IS", "EU"],
    ["63", "Israel", "IL", "AS"],
    ["4", "Italy", "IT", "EU"],
    ["156", "Ethiopia", "ET", "AF"],
    ["94", "Jamaica", "JM", "NA"],
    ["138", "Cambodia", "KH", "AS"],
    ["112", "Kazakhstan", "KZ", "AS"],
    ["95", "Kenya", "KE", "AF"],
    ["102", "Kyrgyzstan", "KG", "AS"],
    ["53", "Latvia", "LV", "EU"],
    ["84", "Luxembourg", "LU", "EU"],
    ["117", "Liechtenstein", "LI", "EU"],
    ["66", "Lithuania", "LT", "EU"],
    ["120", "Lebanon", "LB", "AS"],
    ["159", "Madagascar", "MG", "AF"],
    ["51", "Hungary", "HU", "EU"],
    ["45", "Malaysia", "MY", "AS"],
    ["101", "Malta", "MT", "EU"],
    ["6", "Mexico", "MX", "NA"],
    ["33", "Egypt", "EG", "AF"],
    ["135", "Mozambique", "MZ", "AF"],
    ["103", "Moldova", "MD", "EU"],
    ["119", "Mongolia", "MN", "AS"],
    ["161", "Myanmar", "MM", "AS"],
    ["14", "Netherlands", "NL", "EU"],
    ["168", "Nepal", "NP", "AS"],
    ["111", "Nicaragua", "NI", "NA"],
    ["75", "Nigeria", "NG", "AF"],
    ["22", "Japan", "JP", "AS"],
    ["9", "Norway", "NO", "EU"],
    ["93", "Northern Ireland", "GB", "EU"],
    ["145", "Uzbekistan", "UZ", "AS"],
    ["15", "Oceania", "AU", "OC"],
    ["134", "Oman", "OM", "AS"],
    ["39", "Austria", "AT", "EU"],
    ["71", "Pakistan", "PK", "AS"],
    ["148", "Palestine", "PS", "AS"],
    ["96", "Panama", "PA", "NA"],
    ["72", "Paraguay", "PY", "SA"],
    ["23", "Peru", "PE", "SA"],
    ["55", "Philippines", "PH", "AS"],
    ["24", "Poland", "PL", "EU"],
    ["25", "Portugal", "PT", "EU"],
    ["31", "Thailand", "TH", "AS"],
    ["165", "Puerto Rico", "PR", "NA"],
    ["155", "DR Congo", "CD", "AF"],
    ["88", "Dominican Republic", "DO", "NA"],
    ["37", "Romania", "RO", "EU"],
    ["35", "Russia", "RU", "EU"],
    ["157", "Saint Vincent and the Grenadines", "VC", "NA"],
    ["104", "Georgia", "GE", "AS"],
    ["163", "San Marino", "SM", "EU"],
    ["149", "São Tomé e Príncipe", "ST", "AF"],
    ["79", "Saudi Arabia", "SA", "AS"],
    ["46", "Switzerland", "CH", "EU"],
    ["26", "Scotland", "GB", "EU"],
    ["121", "Senegal", "SN", "AF"],
    ["97", "North Macedonia", "MK", "EU"],
    ["98", "Albania", "AL", "EU"],
    ["47", "Singapore", "SG", "AS"],
    ["64", "Slovenia", "SI", "EU"],
    ["67", "Slovakia", "SK", "EU"],
    ["27", "South Africa", "ZA", "AF"],
    ["57", "Serbia", "RS", "EU"],
    ["152", "Sri Lanka", "LK", "AS"],
    ["12", "Finland", "FI", "EU"],
    ["113", "Suriname", "SR", "SA"],
    ["140", "Syria", "SY", "AS"],
    ["1", "Sweden", "SE", "EU"],
    ["142", "Tanzania", "TZ", "AF"],
    ["80", "Tunisia", "TN", "AF"],
    ["110", "Trinidad & Tobago", "TT", "NA"],
    ["32", "Turkey", "TR", "AS"],
    ["143", "Uganda", "UG", "AF"],
    ["68", "Ukraine", "UA", "EU"],
    ["83", "United Arab Emirates", "AE", "AS"],
    ["28", "Uruguay", "UY", "SA"],
    ["8", "USA", "US", "NA"],
    ["29", "Venezuela", "VE", "SA"],
    ["70", "Vietnam", "VN", "AS"],
    ["162", "Zambia", "ZM", "AF"],
    ["169", "Guyana", "GY", "SA"],
    ["170", "Tahiti", "PF", "OC"],
    ["171", "Guinea", "GN", "AF"],
]
