default_language_version:
  python: python3.7

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        types: [python]

  # ignore typing for now
  # - repo: local
  #   hooks:
  #     - id: mypy
  #       name: mypy
  #       entry: mypy
  #       language: system
  #       types: [python]
  #       args: [--strict]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--check]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--check,--profile=black]
